---

- name: インフラの構築
  hosts: all
  roles:
    - ssh
    - user
    - host
    - apt
    - make
    - vim
    - git
    - docker
    - ufw
    - python
    - systemd
    - timezone

- name: ディスプレイの設定
  hosts: display
  roles:
    - display
