repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --config=api/.flake8

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --settings-path=api/.isort.cfg

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.326
    hooks:
      - id: pyright
