- name: ホスト名の変更
  become: yes
  hostname:
    name: "{{ hostname }}"

- name: プロンプトの変更
  become: yes
  lineinfile:
    dest: /home/takashi/.bashrc
    line: "export PS1='{{ prompt }} '"
  when: not ansible_check_mode

- name: ログインメッセージの変更
  become: yes
  lineinfile:
    dest: /etc/motd
    line: "{{ item }}"
  loop:
    - 第三次冷却終了。
    - フライホイール回転停止。接続を解除。
    - 補助電圧に問題なし。
    - 停止信号プラグ、排出終了。
    - 了解。エントリープラグ挿入。脊髄伝導システムを開放。接続準備。
    - 探査針、打ち込み完了。プラグ深度は20を維持。精神汚染計測値は基準範囲内プラス0.2からマイナス0.5を維持。
    - インテリア固定終了。了解、第一次コンタクト。
    - エントリープラグ注水。
    - 主電源接続完了。
    - 了解、第二次コンタクトに入ります。インターフェイスを接続。
    - A10神経接続、異常なし。LCL電化状態は正常。
    - 思考形態は日本語を基礎原則としてフィックス、初期コンタクト、全て問題なし。
    - コミュニケーション回線、開きます。リスト1405までオールクリア。シナプス計測、シンクロ率41.3％
    - ハーモニクス、全て正常値。暴走、ありません。
