repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --config=api/.flake8

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --settings-path=api/.isort.cfg

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.326
    hooks:
      - id: pyright
        args:
          - --pythonpath
          - api/.venv/bin/python

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.19.0
    hooks:
      - id: ansible-lint
        name: ansible-lint
        always_run: true
        pass_filenames: false
        args:
          - -c
          - hooks/.ansible-lint-pre-commit
        additional_dependencies:
          - ansible==8.3.0
