- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
  when: not ansible_check_mode

- name: Install Pipenv
  become: true
  become_user: takashi
  ansible.builtin.pip:
    name:
      - pipenv
  when: not ansible_check_mode

- name: Add path to .bash_profile
  become: true
  ansible.builtin.lineinfile:
    path: /home/takashi/.bash_profile
    line: export PATH="$HOME/.local/bin:$PATH"

- name: Apply .bash_profile
  become: true
  become_user: takashi
  ansible.builtin.shell: source /home/takashi/.bash_profile
  args:
    executable: /bin/bash
  when: not ansible_check_mode
