- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
  when: not ansible_check_mode

- name: Install Pipenv
  ansible.builtin.pip:
    name:
      - pipenv
  when: not ansible_check_mode
