---

services:
  traefik:
    image: "traefik:v2.10"
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./config:/etc/traefik/config"
      - "./certs:/etc/traefik/certs"
    restart: always

networks:
  default:
    name: uyunpunion-network
    external: true
