services:
  traefik:
    image: "traefik:v2.8"
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./api.toml:/etc/traefik/api.toml"
    restart: always

networks:
  default:
    name: uyunpunion-network
    external: true
