[log]
    level = "DEBUG"

[api]
    insecure = true

[providers.docker]
#     exposedByDefault = false

[providers.file]
    filename = "/etc/traefik/external.toml"

[entryPoints]
    [entryPoints.web]
        address = ":80"
