[log]
    level = "DEBUG"

[api]
    dashboard = true

[providers.file]
    directory = "/etc/traefik/config"
    watch = true

[entryPoints]
    [entryPoints.web]
        address = ":80"

    [entryPoints.websecure]
        address = ":443"

[tls]
    [tls.stores]
        [tls.stores.default]
            [tls.stores.default.defaultCertificate]
                certFile = "/etc/traefik/certs/selfsigned.crt"
                keyFile = "/etc/traefik/certs/selfsigned.key"
