[log]
    level = "DEBUG"

[api]
    dashboard = true
    # insecure = true

[providers.file]
    directory = "/etc/traefik/config"
    watch = true

[entryPoints]
    [entryPoints.web]
        address = ":80"
