- name: Install required packages for Docker
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  when: not ansible_check_mode

- name: Add Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: not ansible_check_mode

- name: Add repository to APT
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  when: not ansible_check_mode

- name: Add takashi user to docker group
  become: true
  ansible.builtin.user:
    name: takashi
    groups: docker
    append: true

- name: Start docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
  when: not ansible_check_mode
