---

- name: Install Vim
  become: true
  ansible.builtin.apt:
    name: vim
  when: not ansible_check_mode
  tags: vim

- name: Copy .vimrc
  become: true
  ansible.builtin.copy:
    src: files/.vimrc
    dest: /home/takashi/.vimrc
    owner: takashi
    group: uyunpunion
    mode: "0755"
  tags: vim
